# Secrets Required
#  GPG_SIGNING_KEY
#  GPG_SIGNING_PASSPHRASE
#  OSSRH_USERNAME
#  OSSRH_PASSWORD

name: Publish
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${{ inputs.version }}${GITHUB_REF/refs\/tags\//}

      - name: Assemble Packages
        run: ./gradlew -xtest jar javadocJar kotlinSourcesJar

      - name: Sign Packages
        run: ./gradlew -xjar signMavenPublication
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}

      - name: Publish Packages
        run: ./gradlew publishToSonatype closeAndReleaseStagingRepositories
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_VERSION: ${{ steps.get_version.outputs.VERSION }}
